import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Card, CardHeader, CardBody, CardFooter,Stack,VStack,Heading,Text,Divider,ButtonGroup,Button,Image,Center} from '@chakra-ui/react'
import Header from '../component/header'
import React,{ useEffect, useState} from 'react'


export default function Home() {
  const [backendData, setBackendData] = useState({})


  useEffect(() => {
    fetch('/api/sd')
      .then((res) => res.json())
      .then((data) => {
        setBackendData(data)
        console.log(data)
      })
  }, [])

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
      <Card maxW='md'>
          <CardBody>
            <Center>
              <Image
                src='/assets/face-id.png'
                boxSize='200px'
              />
            </Center>
            <Stack mt='6' spacing='3'>
              <Center>
                <Button colorScheme='teal' size='lg'>
                  FaceID Login
   
                </Button>
              </Center>
            </Stack>
          </CardBody>
          <Divider />
          <CardFooter>
            <ButtonGroup spacing='2'>
              <Button variant='solid' colorScheme='blue'>
                Login by username and pw
              </Button>
              <Button variant='ghost' colorScheme='blue'>
                register
              </Button>
            </ButtonGroup>
          </CardFooter>
        </Card>
      </main>
    </>
  )
}
